apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::829789393256:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-UGZBHF5GLSYH\n
    \ username: system:node:{{EC2PrivateDNSName}}\n- groups: \n  - system:masters\n
    \ rolearn: arn:aws:iam::829789393256:role/UdacityFlaskDeployCBKubectlRole\n  username:
    build\n"
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-12T17:56:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3003"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 0f582c19-131a-4066-a327-f281b19b9ea4
