apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::829789393256:role/eksctl-simple-jwt-api2-nodegroup-NodeInstanceRole-1PIDHKE6W5JJ
      username: system:node:{{EC2PrivateDNSName}}
    - groups: 
      - system:masters
      rolearn: arn:aws:iam::829789393256:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-12T10:20:17Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2246"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 63e7d93e-a178-4310-a163-417c199c8157
