apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::829789393256:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-H0YJJ9Z3ICWP
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::829789393256:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
      - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-13T09:17:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "8808"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a65860d4-8ad3-4219-ba4c-fea5f94f7eea
